// Structured data (schema.org JSON-LD) for search engines. Built only from content already on the page.
import type { Block, PageDef } from "@/content/types";
import { site } from "@/content/site";
import { findPage } from "@/lib/pages";

const abs = (path: string) => new URL(path, site.url).toString();

// Brackets mark accent words in titles; search engines should see plain text.
const plain = (text: string) => text.replace(/[[\]]/g, "");

export function organization() {
  const sameAs = site.social.map((item) => item.href).filter((href) => /^https?:\/\//.test(href));
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: site.name,
    url: abs("/"),
    logo: abs("/images/logo-mark-512.png"),
    description: site.description,
    ...(sameAs.length ? { sameAs } : {}),
  };
}

export function website() {
  return { "@context": "https://schema.org", "@type": "WebSite", name: site.name, url: abs("/") };
}

// Home > parent pages that exist > this page. Segments without their own page are skipped.
export function breadcrumbs(path: string, title: string, parents: { name: string; path: string }[] = []) {
  const segments = path.split("/").filter(Boolean);
  const trail = [{ name: "Home", path: "/" }, ...parents];
  segments.slice(0, -1).forEach((_, index) => {
    const parent = findPage(segments.slice(0, index + 1));
    if (parent) trail.push({ name: plain(parent.meta.title), path: parent.path });
  });
  trail.push({ name: plain(title), path });
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, item: abs(item.path) })),
  };
}

export function faqPage(items: { q: string; a: string }[]) {
  if (!items.length) return null;
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((item) => ({ "@type": "Question", name: item.q, acceptedAnswer: { "@type": "Answer", text: item.a } })),
  };
}

// FAQ blocks, plus accordion items phrased as questions (the FAQ page is built from accordions).
export function faqItems(blocks: Block[]) {
  return blocks.flatMap((block) => {
    if (block.draft) return [];
    if (block.type === "faq") return block.items;
    if (block.type === "accordion") return block.items.filter((item) => item.title.trim().endsWith("?")).map((item) => ({ q: item.title, a: item.text }));
    return [];
  });
}

// Share image generated by app/opengraph-image.tsx. Pages that set their own openGraph must list it again,
// because Next.js replaces the parent openGraph instead of merging it.
export const shareImage = { url: "/opengraph-image", width: 1200, height: 630, alt: site.name };

export function article(post: { title: string; excerpt: string; date: string; slug: string }) {
  return {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: post.title,
    description: post.excerpt,
    datePublished: post.date,
    url: abs(`/insights/${post.slug}/`),
    publisher: { "@type": "Organization", name: site.name, logo: { "@type": "ImageObject", url: abs("/images/logo-mark-512.png") } },
  };
}

export function pageSchemas(page: PageDef) {
  return [breadcrumbs(page.path, page.meta.title), faqPage(faqItems(page.blocks))].filter(Boolean);
}
